server:
    port: 9999
    context-path: /auth

spring:
  profiles:
    active: techopcf
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://${vcap.services.cleardb.[0].credentials.hostname:localhost}:${vcap.services.cleardb.[0].credentials.port:3303}/${vcap.services.cleardb.[0].credentials.name:player}
    username: ${vcap.services.cleardb.[0].credentials.username:dbuser}
    password: ${vcap.services.cleardb.[0].credentials.password:password}
    driver-class-name: com.mysql.jdbc.Driver

# IMPORTANT NOTICE: 
# You have to replace this keypair and make sure the private key remains private!
#

config:
   oauth2:
        ui-uri: ${vcap.services.ui-service.credentials.uri:http://localhost:8080/}
        admin-uri: ${vcap.services.admin-service.credentials.uri:http://localhost:9000/admin/}
        # openssl genrsa -out jwt.pem 2048
        # openssl rsa -in jwt.pem
        privateKey: |
            -----BEGIN RSA PRIVATE KEY-----
            MIICXQIBAAKBgQDNQZKqTlO/+2b4ZdhqGJzGBDltb5PZmBz1ALN2YLvt341pH6i5
            mO1V9cX5Ty1LM70fKfnIoYUP4KCE33dPnC7LkUwE/myh1zM6m8cbL5cYFPyP099t
            hbVxzJkjHWqywvQih/qOOjliomKbM9pxG8Z1dB26hL9dSAZuA8xExjlPmQIDAQAB
            AoGAImnYGU3ApPOVtBf/TOqLfne+2SZX96eVU06myDY3zA4rO3DfbR7CzCLE6qPn
            yDAIiW0UQBs0oBDdWOnOqz5YaePZu/yrLyj6KM6Q2e9ywRDtDh3ywrSfGpjdSvvo
            aeL1WesBWsgWv1vFKKvES7ILFLUxKwyCRC2Lgh7aI9GGZfECQQD84m98Yrehhin3
            fZuRaBNIu348Ci7ZFZmrvyxAIxrV4jBjpACW0RM2BvF5oYM2gOJqIfBOVjmPwUro
            bYEFcHRvAkEAz8jsfmxsZVwh3Y/Y47BzhKIC5FLaads541jNjVWfrPirljyCy1n4
            sg3WQH2IEyap3WTP84+csCtsfNfyK7fQdwJBAJNRyobY74cupJYkW5OK4OkXKQQL
            Hp2iosJV/Y5jpQeC3JO/gARcSmfIBbbI66q9zKjtmpPYUXI4tc3PtUEY8QsCQQCc
            xySyC0sKe6bNzyC+Q8AVvkxiTKWiI5idEr8duhJd589H72Zc2wkMB+a2CEGo+Y5H
            jy5cvuph/pG/7Qw7sljnAkAy/feClt1mUEiAcWrHRwcQ71AoA0+21yC9VkqPNrn3
            w7OEg8gBqPjRlXBNb00QieNeGGSkXOoU6gFschR22Dzy
            -----END RSA PRIVATE KEY-----

        # openssl rsa -in jwt.pem -pubout
        publicKey: |
            -----BEGIN PUBLIC KEY-----
            MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDNQZKqTlO/+2b4ZdhqGJzGBDlt
            b5PZmBz1ALN2YLvt341pH6i5mO1V9cX5Ty1LM70fKfnIoYUP4KCE33dPnC7LkUwE
            /myh1zM6m8cbL5cYFPyP099thbVxzJkjHWqywvQih/qOOjliomKbM9pxG8Z1dB26
            hL9dSAZuA8xExjlPmQIDAQAB
            -----END PUBLIC KEY-----
       
       
logging:
  level:
    org.springframework.security: INFO
    org.springframework.cloud.netflix: INFO
    com.netflix.zuul: INFO
    com.makeurpicks: DEBUG
    
---    
spring:
  profiles: container
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://${MYSQL_PORT_3306_TCP_ADDR:auth-db}:${MYSQL_PORT_3306_TCP_PORT:3306}/${MYSQL_ENV_MYSQL_DATABASE:player}
    username: ${MYSQL_USER:dbuser}
    password: ${MYSQL_PASSWORD:password}
    driver-class-name: com.mysql.jdbc.Driver   
    
---    
spring:
  profiles: pcf
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://${vcap.services.cleardb.[0].credentials.hostname:localhost}:${vcap.services.cleardb.[0].credentials.port:3306}/${vcap.services.cleardb.[0].credentials.name:player}
    username: ${vcap.services.cleardb.[0].credentials.username:dbuser}
    password: ${vcap.services.cleardb.[0].credentials.password:password}
    driver-class-name: com.mysql.jdbc.Driver
eureka:
#  instance:
#    prefer-ip-address: true
#    hostname: ${vcap.application.uris[0]:eureka-leagues-myp.cfapps.io}
#    nonSecurePort: ${vcap.services.eureka-service.credentials.port:${server.port}}
#    leaseRenewalIntervalInSeconds: 10
#    metadataMap:
#      instanceId: ${vcap.application.instance_id:${spring.application.name}:${random.value}}
#  client:
#    serviceUrl:
#      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://eureka-leagues-myp.cfapps.io}/eureka/
  instance:
    prefer-ip-address: false
    hostname: auth-server-myp.cfapps.io
    nonSecurePort: 9999
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://eureka-leagues-myp.cfapps.io/eureka/
config:
   oauth2:
        ui-uri: ${vcap.services.ui-service.credentials.uri:https://league-myp.cfapps.io/}
        admin-ssluri: ${vcap.services.admin-service.credentials.uri:https://admin-myp.cfapps.io/admin/}
        admin-uri: ${vcap.services.admin-service.credentials.uri:http://admin-myp.cfapps.io/admin/}
        localadmin-uri: ${vcap.services.admin-service.credentials.uri:http://localhost:9000/admin/}
        privateKey: |
            -----BEGIN RSA PRIVATE KEY-----
            MIICXQIBAAKBgQDNQZKqTlO/+2b4ZdhqGJzGBDltb5PZmBz1ALN2YLvt341pH6i5
            mO1V9cX5Ty1LM70fKfnIoYUP4KCE33dPnC7LkUwE/myh1zM6m8cbL5cYFPyP099t
            hbVxzJkjHWqywvQih/qOOjliomKbM9pxG8Z1dB26hL9dSAZuA8xExjlPmQIDAQAB
            AoGAImnYGU3ApPOVtBf/TOqLfne+2SZX96eVU06myDY3zA4rO3DfbR7CzCLE6qPn
            yDAIiW0UQBs0oBDdWOnOqz5YaePZu/yrLyj6KM6Q2e9ywRDtDh3ywrSfGpjdSvvo
            aeL1WesBWsgWv1vFKKvES7ILFLUxKwyCRC2Lgh7aI9GGZfECQQD84m98Yrehhin3
            fZuRaBNIu348Ci7ZFZmrvyxAIxrV4jBjpACW0RM2BvF5oYM2gOJqIfBOVjmPwUro
            bYEFcHRvAkEAz8jsfmxsZVwh3Y/Y47BzhKIC5FLaads541jNjVWfrPirljyCy1n4
            sg3WQH2IEyap3WTP84+csCtsfNfyK7fQdwJBAJNRyobY74cupJYkW5OK4OkXKQQL
            Hp2iosJV/Y5jpQeC3JO/gARcSmfIBbbI66q9zKjtmpPYUXI4tc3PtUEY8QsCQQCc
            xySyC0sKe6bNzyC+Q8AVvkxiTKWiI5idEr8duhJd589H72Zc2wkMB+a2CEGo+Y5H
            jy5cvuph/pG/7Qw7sljnAkAy/feClt1mUEiAcWrHRwcQ71AoA0+21yC9VkqPNrn3
            w7OEg8gBqPjRlXBNb00QieNeGGSkXOoU6gFschR22Dzy
            -----END RSA PRIVATE KEY-----

        # openssl rsa -in jwt.pem -pubout
        publicKey: |
            -----BEGIN PUBLIC KEY-----
            MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDNQZKqTlO/+2b4ZdhqGJzGBDlt
            b5PZmBz1ALN2YLvt341pH6i5mO1V9cX5Ty1LM70fKfnIoYUP4KCE33dPnC7LkUwE
            /myh1zM6m8cbL5cYFPyP099thbVxzJkjHWqywvQih/qOOjliomKbM9pxG8Z1dB26
            hL9dSAZuA8xExjlPmQIDAQAB
            -----END PUBLIC KEY-----
---    
spring:
  profiles: techopcf
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://40.121.212.183:${vcap.services.p-mysql.[0].credentials.port:3306}/${vcap.services.p-mysql.[0].credentials.name:cf_0619e413_5337_476d_98b7_2e1d996aa224}
    username: ${vcap.services.p-mysql.[0].credentials.username:v3UBiVC4yFOPqQRX}
    password: ${vcap.services.p-mysql.[0].credentials.password:6Hma540BY1h5R1i6}
    driver-class-name: com.mysql.jdbc.Driver
eureka:
#  instance:
#    prefer-ip-address: true
#    hostname: ${vcap.application.uris[0]:eureka-leagues-myp.apps.techolution.com}
#    nonSecurePort: ${vcap.services.eureka-service.credentials.port:${server.port}}
#    leaseRenewalIntervalInSeconds: 10
#    metadataMap:
#      instanceId: ${vcap.application.instance_id:${spring.application.name}:${random.value}}
#  client:
#    serviceUrl:
#      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://eureka-leagues-myp.apps.techolution.com}/eureka/
  instance:
    prefer-ip-address: false
    hostname: auth-server-myp.apps.techolution.com
    nonSecurePort: 9999
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://eureka-leagues-myp.apps.techolution.com/eureka/
config:
   oauth2:
        ui-uri: ${vcap.services.ui-service.credentials.uri:https://league-myp.apps.techolution.com/}
        admin-ssluri: ${vcap.services.admin-service.credentials.uri:https://admin-myp.apps.techolution.com/admin/}
        admin-uri: ${vcap.services.admin-service.credentials.uri:http://admin-myp.apps.techolution.com/admin/}
        localadmin-uri: ${vcap.services.admin-service.credentials.uri:http://localhost:9000/admin/}
        privateKey: |
            -----BEGIN RSA PRIVATE KEY-----
            MIICXQIBAAKBgQDNQZKqTlO/+2b4ZdhqGJzGBDltb5PZmBz1ALN2YLvt341pH6i5
            mO1V9cX5Ty1LM70fKfnIoYUP4KCE33dPnC7LkUwE/myh1zM6m8cbL5cYFPyP099t
            hbVxzJkjHWqywvQih/qOOjliomKbM9pxG8Z1dB26hL9dSAZuA8xExjlPmQIDAQAB
            AoGAImnYGU3ApPOVtBf/TOqLfne+2SZX96eVU06myDY3zA4rO3DfbR7CzCLE6qPn
            yDAIiW0UQBs0oBDdWOnOqz5YaePZu/yrLyj6KM6Q2e9ywRDtDh3ywrSfGpjdSvvo
            aeL1WesBWsgWv1vFKKvES7ILFLUxKwyCRC2Lgh7aI9GGZfECQQD84m98Yrehhin3
            fZuRaBNIu348Ci7ZFZmrvyxAIxrV4jBjpACW0RM2BvF5oYM2gOJqIfBOVjmPwUro
            bYEFcHRvAkEAz8jsfmxsZVwh3Y/Y47BzhKIC5FLaads541jNjVWfrPirljyCy1n4
            sg3WQH2IEyap3WTP84+csCtsfNfyK7fQdwJBAJNRyobY74cupJYkW5OK4OkXKQQL
            Hp2iosJV/Y5jpQeC3JO/gARcSmfIBbbI66q9zKjtmpPYUXI4tc3PtUEY8QsCQQCc
            xySyC0sKe6bNzyC+Q8AVvkxiTKWiI5idEr8duhJd589H72Zc2wkMB+a2CEGo+Y5H
            jy5cvuph/pG/7Qw7sljnAkAy/feClt1mUEiAcWrHRwcQ71AoA0+21yC9VkqPNrn3
            w7OEg8gBqPjRlXBNb00QieNeGGSkXOoU6gFschR22Dzy
            -----END RSA PRIVATE KEY-----

        # openssl rsa -in jwt.pem -pubout
        publicKey: |
            -----BEGIN PUBLIC KEY-----
            MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDNQZKqTlO/+2b4ZdhqGJzGBDlt
            b5PZmBz1ALN2YLvt341pH6i5mO1V9cX5Ty1LM70fKfnIoYUP4KCE33dPnC7LkUwE
            /myh1zM6m8cbL5cYFPyP099thbVxzJkjHWqywvQih/qOOjliomKbM9pxG8Z1dB26
            hL9dSAZuA8xExjlPmQIDAQAB
            -----END PUBLIC KEY-----