server:
  port: 8081
#  context-path: /leagues

security:
  oauth2:
    resource:
      jwt:
#        key-value: |
#            -----BEGIN PUBLIC KEY-----
#            MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDNQZKqTlO/+2b4ZdhqGJzGBDlt
#            b5PZmBz1ALN2YLvt341pH6i5mO1V9cX5Ty1LM70fKfnIoYUP4KCE33dPnC7LkUwE
#            /myh1zM6m8cbL5cYFPyP099thbVxzJkjHWqywvQih/qOOjliomKbM9pxG8Z1dB26
#            hL9dSAZuA8xExjlPmQIDAQAB
#            -----END PUBLIC KEY-----
        key-uri: "http://localhost:9999/auth/oauth/token_key"
        
#security:
#  oauth2:
#    resource:
#      userInfoUri: http://localhost:9999/uaa/user

logging:
  level:
    org.springframework.security: DEBUG